wait on deployments not pods

diff --git a/ksbctl b/ksbctl
--- a/ksbctl
+++ b/ksbctl
@@ -138,29 +138,48 @@ function startMinikube {
 }
 
 function getPodName {
-	kubectl get pods --no-headers=true -n $NAMESPACE | awk '/^'$1'/ {print $1}'
+	kubectl get pods --no-headers=true -n $NAMESPACE | awk '/^'$1'/ {print $1}' | head -1
+}
+
+# wait for a deployment to be ready
+function waitDeploymentReady {
+	typeset deploymentName
+	deploymentName=$1
+	if [[ -n $deploymentName ]]; then
+		if kubectl get deployment --no-headers=true -n $NAMESPACE $deploymentName > /dev/null 2>&1; then
+			echo -n "[INFO]Waiting for deployment $NAMESPACE:$deploymentName to be ready."
+			while [[ $( kubectl get deployment --no-headers=true -n $NAMESPACE $deploymentName | awk -F '[ /]+' '{print $2 - $3}' ) -ne 0 ]]; do
+				echo -n .
+				sleep 5
+			done
+		else
+			echo "[FATAL]Cannot find a deployment matching '$1'"
+			exit 1
+		fi
+	fi
+	echo " done"
 }
 
 # wait for a pod to start
 function waitPodReady {
-	typeset podname
-	podname=$(getPodName $1)
-	if [[ -n $podname ]]; then
+	typeset podName
+	podName=$(getPodName $1)
+	if [[ -n $podName ]]; then
 
-		echo -n "[INFO]Waiting for $NAMESPACE:$podname to start."
-		while [[ $( kubectl get pods --no-headers=true -n $NAMESPACE "$podname" | awk -F '[ /]+' '{print $2}' ) -ne 1 ]]; do
+		echo -n "[INFO]Waiting for pod $NAMESPACE:$podName to be ready."
+		while [[ $( kubectl get pods --no-headers=true -n $NAMESPACE "$podName" | awk -F '[ /]+' '{print $2}' ) -ne 1 ]]; do
 			echo -n .
 			sleep 5
-			if kubectl logs -n $NAMESPACE "$podname" 2>&1 | grep -q 'trying and failing to pull image'; then
-				echo; echo "[FATAL]Unable to pull image for '$podname'"
+			if kubectl logs -n $NAMESPACE "$podName" 2>&1 | grep -q 'trying and failing to pull image'; then
+				echo; echo "[FATAL]Unable to pull image for '$podName'"
 				exit 1
 			fi
 			# Pending pods mean there aren't enough resources. Warn and exit
-			if kubectl get pods --no-headers=true -n $NAMESPACE "$podname" | grep -qi 'pending'; then
+			if kubectl get pods --no-headers=true -n $NAMESPACE "$podName" | grep -qi 'pending'; then
 				# give it some time to find a place for the pod
 				sleep 5
-				if kubectl get pods --no-headers=true -n $NAMESPACE "$podname" | grep -qi 'pending'; then
-					echo; echo "[FATAL]Not enough resources in the cluster to run $podname"
+				if kubectl get pods --no-headers=true -n $NAMESPACE "$podName" | grep -qi 'pending'; then
+					echo; echo "[FATAL]Not enough resources in the cluster to run $podName"
 					exit 1
 				fi
 			fi
@@ -449,14 +468,18 @@ if [[ $# -gt 0 ]]; then
 				fi
 				createNamespace
 				echo "[INFO]Starting redis and mongo"
-				applyYAML mongo.yaml redis.yaml # grpc-plugin.yaml
-				waitPodReady control-redis
-				waitPodReady mongo
+				applyYAML mongo.yaml redis-control.yaml # grpc-plugin.yaml
+				waitDeploymentReady control-redis
+				waitDeploymentReady mongo-db
 				echo "[INFO]Starting dashboard, pump and gateway"
 				# setup configmaps first
 				applyYAML tyk-dashboard-configmap-mongo.yaml tyk-gateway-configmap-control.yaml tyk-pump-configmap-mongo.yaml
-				applyYAML tyk-dashboard.yaml tyk-gateway.yaml tyk-dashboard-svc.yaml tyk-gateway-svc.yaml tyk-pump.yaml
-				waitPodReady tyk-dashboard
+				# create dashboard, control gateway and pump deployments
+				applyYAML tyk-dashboard.yaml tyk-gateway-control.yaml tyk-pump.yaml
+				# create dashboard and control gateway services
+				applyYAML tyk-dashboard-svc.yaml tyk-gateway-svc-control.yaml 
+				waitDeploymentReady tyk-dashboard
+				waitDeploymentReady control-gateway
 				licenseDashboard
 				addDashboardUser
 				publishAPIs $SCRIPTDIR/APIs/*.json
