ksbctl: retabbed

diff --git a/ksbctl b/ksbctl
--- a/ksbctl
+++ b/ksbctl
@@ -590,23 +590,23 @@ function CrdExists {
 }
 
 function MaskOperatorContext {
-  typeset namespace
-  namespace=$1
-  if CrdExists $namespace operatorcontexts.tyk.tyk.io; then
-    kubectl get operatorcontext $OPERATOR_CONTEXT_NAME -n $namespace -o yaml | yq  '.spec.env.url = "'$OPERATOR_MASK_URL'"' | kubectl apply -n $namespace -f -
-  fi
+	typeset namespace
+	namespace=$1
+	if CrdExists $namespace operatorcontexts.tyk.tyk.io; then
+		kubectl get operatorcontext $OPERATOR_CONTEXT_NAME -n $namespace -o yaml | yq  '.spec.env.url = "'$OPERATOR_MASK_URL'"' | kubectl apply -n $namespace -f -
+	fi
 }
 
 function RemoveTykCRDs {
-  typeset namespace
-  typeset CRD
-  namespace=$1
-  for CRD in portalapicatalogues apidescriptions securitypolicies apidefinitions supergraphs subgraphs portalconfigs; do
-    if CrdExists $namespace $CRD; then
-      echo "[INFO]Removing all $CRD from $namespace"
-      kubectl delete $CRD --all -n $namespace
-    fi
-  done
+	typeset namespace
+	typeset CRD
+	namespace=$1
+	for CRD in portalapicatalogues apidescriptions securitypolicies apidefinitions supergraphs subgraphs portalconfigs; do
+		if CrdExists $namespace $CRD; then
+			echo "[INFO]Removing all $CRD from $namespace"
+			kubectl delete $CRD --all -n $namespace
+		fi
+	done
 }
 
 function OperatorContextExists {
@@ -616,7 +616,6 @@ function OperatorContextExists {
 	fi
 	return 1
 }
-
 
 # Process the YAML with envsubst to substitute environment variables into them
 # All exported environment varables are available to envsubst but these are the main ones
@@ -762,13 +761,13 @@ function showLogs {
 	typeset pod
 	podPartName=$1
 	pod=$(kubectl get pods -n $NAMESPACE | awk '/'$podPartName'/ {print $1}' | head -1)
-  if [[ -n $pod ]]; then
-	  echo "[INFO]kubectl logs -n $NAMESPACE $pod -f"
-	  kubectl logs -n $NAMESPACE $pod -f
-  else
-    echo "[FATAL]'$podPartName' not found in namespace $NAMESPACE"
-    kubectl get pods -n $NAMESPACE
-  fi
+	if [[ -n $pod ]]; then
+		echo "[INFO]kubectl logs -n $NAMESPACE $pod -f"
+		kubectl logs -n $NAMESPACE $pod -f
+	else
+		echo "[FATAL]'$podPartName' not found in namespace $NAMESPACE"
+		kubectl get pods -n $NAMESPACE
+	fi
 }
 
 # Hybrid needs to be enabled for MDCB installs
@@ -1248,8 +1247,8 @@ if [[ $# -gt 0 ]]; then
 			for NAMESPACE in $(getNamespaceNames $*); do
 				if namespaceExists $NAMESPACE; then
 					echo "[INFO]Deleting Namespace $NAMESPACE"
-          MaskOperatorContext $NAMESPACE
-          RemoveTykCRDs $NAMESPACE
+					MaskOperatorContext $NAMESPACE
+					RemoveTykCRDs $NAMESPACE
 					if OperatorContextExists $NAMESPACE ]]; then
 						echo "[INFO]Deleting OperatorContext from $NAMESPACE"
 						echo "[INFO]kubectl delete OperatorContext --all -n $NAMESPACE"
@@ -1268,13 +1267,13 @@ if [[ $# -gt 0 ]]; then
 			shift
 			if [[ $# -lt 1 ]]; then
 				# give info on all if none given
-        typeset allSandboxes
-        allSandboxes=$(getAllSandboxes)
-        if [[ $allSandboxes = "" ]]; then
-          echo "[INFO]No sandboxes configured"
-          exit 0
-        fi
-        set $allSandboxes
+				typeset allSandboxes
+				allSandboxes=$(getAllSandboxes)
+				if [[ $allSandboxes = "" ]]; then
+					echo "[INFO]No sandboxes configured"
+					exit 0
+				fi
+				set $allSandboxes
 			fi
 			for NAMESPACE in $(getNamespaceNames $*); do
 				if namespaceExists $NAMESPACE; then
@@ -1395,28 +1394,28 @@ if [[ $# -gt 0 ]]; then
 				sleep $POD_MONITOR_FREQ
 			done
 			;;
-    operatorlogs)
-      typeset operatorPodName
-      operatorPodName=$(kubectl get pods -n tyk-operator-system --no-headers=true | awk '{print $1}')
-      if [[ -n $operatorPodName ]]; then
-        echo "[INFO]kubectl logs $operatorPodName -n tyk-operator-system -f"
-        kubectl logs $operatorPodName -n tyk-operator-system -f
-      else
-        echo "[FATAL]No operator pod found"
-        exit 1
-      fi
-      ;;
+		operatorlogs)
+			typeset operatorPodName
+			operatorPodName=$(kubectl get pods -n tyk-operator-system --no-headers=true | awk '{print $1}')
+			if [[ -n $operatorPodName ]]; then
+				echo "[INFO]kubectl logs $operatorPodName -n tyk-operator-system -f"
+				kubectl logs $operatorPodName -n tyk-operator-system -f
+			else
+				echo "[FATAL]No operator pod found"
+				exit 1
+			fi
+			;;
 		pods)
 			shift
 			if [[ $# -lt 1 ]]; then
 				# give info on all if none given
-        typeset allSandboxes
-        allSandboxes=$(getAllSandboxes)
-        if [[ $allSandboxes = "" ]]; then
-          echo "[INFO]No sandboxes configured"
-          exit 0
-        fi
-        set $allSandboxes
+				typeset allSandboxes
+				allSandboxes=$(getAllSandboxes)
+				if [[ $allSandboxes = "" ]]; then
+					echo "[INFO]No sandboxes configured"
+					exit 0
+				fi
+				set $allSandboxes
 			fi
 			for NAMESPACE in $(getNamespaceNames $*); do
 				if namespaceExists $NAMESPACE; then
