ksbctl: checks for dependencies

diff --git a/ksbctl b/ksbctl
--- a/ksbctl
+++ b/ksbctl
@@ -2,6 +2,8 @@
 
 # command to manage tyk instances in distinct namespaces
 
+PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:$PATH
+
 # Dependencies
 #  minikube to run a local kubernetes
 #  ksh to support arrays. the Mac version of bash doesn't
@@ -14,16 +16,17 @@
 #			(done) create index of versions that can be used
 #			(done) use envsubst to create sandboxes of different versions
 #			Save versions in label and display them in the info/list commands
-#		test for needed commands
-#			minikube
-#				allow creation of cluster if not present
-#			envsubst
-#			mongo shell
-#			redis-cli
+#			Set versions for mongo/redis and postgresql too
+#		(done) test for command dependencies
+#			(done) minikube
+#				(done) allow creation of cluster if not present
+#			(done) envsubst mongo shell redis-cli
 #		test on other platforms
 #			windows
 #			MacOS
 #				M1
+#		Better checking of pod startup.
+#			Warn if pods in 'Pending' and exit
 #		(done) expose redis and mongo ports
 #		retrieve credentials from redis
 #			display creds when asked
@@ -63,12 +66,53 @@ else
 	SBX_PASSWORD=""
 fi
 
-# start minikube if it's not already running
+function checkMinikubeInstalled {
+	if ! which minikube >/dev/null
+	then
+		echo "[FATAL]Command 'minikube' not found. Cannot continue"
+		exit 1
+	fi
+}
+
+function checkEnvsubstInstalled {
+	if ! which envsubst >/dev/null
+	then
+		echo "[FATAL]Command 'envsubst' not found. Cannot continue"
+		exit 1
+	fi
+}
+
+function checkRedisCliInstalled {
+	if ! which redis-cli >/dev/null
+	then
+		echo "[FATAL]Command 'redis-cli' not found. Cannot continue"
+		exit 1
+	fi
+}
+
+function checkMongoShellInstalled {
+	if ! which mongo >/dev/null
+	then
+		if which mongosh /dev/null
+		then
+			alias mongo=mongosh
+		else
+			echo "[FATAL]Mongo shell 'mongo' or 'mongosh' not installed. Cannot continue"
+			exit 1
+		fi
+	fi
+}
+
+# check for command dependencies
+checkMinikubeInstalled
+checkRedisCliInstalled
+checkMinikubeInstalled
+
+# create or start minikube if it's not already running
 function startMinikube {
 	if ! minikube status > /dev/null 2>&1 ;then
 		echo "[INFO]Starting minikube"
-		#minikube start --driver docker --cpus max --memory max
-		minikube start
+		minikube start --driver docker --cpus max --memory max
 	fi
 	minikubeIP=$(minikube ip)
 }
